name: Deploy Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install vsce
        run: npm install -g vsce

      - name: Install dependencies
        run: npm ci

      - name: Build Extension
        run: npm run package

      - name: Publish to VSCode Marketplace
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
